name: tarologo
description: "Tarot service"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.1.2
  blurrycontainer: ^2.1.0
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/tarot_photos/1.jpg
    - assets/tarot_photos/2.jpg
    - assets/tarot_photos/3.jpg
    - assets/tarot_photos/4.jpg
    - assets/tarot_photos/5.jpg
    - assets/tarot_photos/6.jpg
    - assets/tarot_photos/7.jpg
    - assets/tarot_photos/8.jpg
    - assets/tarot_photos/9.jpg
    - assets/tarot_photos/10.jpg
    - assets/profile_photo/vova.png
    - assets/profile_photo/SLONYARA.jpg
    - assets/logo/logo.svg

  uses-material-design: true
